config/routes.rb
Rails.application.routes.draw do
  resources :friends
  resources :games
  resources :statistics
  resources :locations
  resources :pieces
  resources :pieces
 

   post 'chat/message' => 'chat#message'
   post 'games/move'  => 'games#move'

   post 'games/create' => 'games#create'
     get 'games/assets/:name.:ext', to: redirect('assets/%{name}.%{ext}')
 
   match ':controller(/:action(/:id))', :via => :get

  devise_for :users, :controllers => { :registrations => "registrations" }

   root 'home#title'

     get 'home/index' => 'home#index'

end

app/models/statistic.rb
class Statistic < ActiveRecord::Base
	belongs_to :User
end

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController
  before_action :set_statistic, only: [:show, :edit, :update, :destroy]

  # GET /statistics
  # GET /statistics.json
  def index
    @statistics = Statistic.all
  end

  # GET /statistics/1
  # GET /statistics/1.json
  def show
  end

  # GET /statistics/new
  def new
    @statistic = Statistic.new
  end

  # GET /statistics/1/edit
  def edit
  end

  # POST /statistics
  # POST /statistics.json
  def create
    @statistic = Statistic.new(statistic_params)

    respond_to do |format|
      if @statistic.save
        format.html { redirect_to @statistic, notice: 'Statistic was successfully created.' }
        format.json { render :show, status: :created, location: @statistic }
      else
        format.html { render :new }
        format.json { render json: @statistic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statistics/1
  # PATCH/PUT /statistics/1.json
  def update
    respond_to do |format|
      if @statistic.update(statistic_params)
        format.html { redirect_to @statistic, notice: 'Statistic was successfully updated.' }
        format.json { render :show, status: :ok, location: @statistic }
      else
        format.html { render :edit }
        format.json { render json: @statistic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statistics/1
  # DELETE /statistics/1.json
  def destroy
    @statistic.destroy
    respond_to do |format|
      format.html { redirect_to statistics_url, notice: 'Statistic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_statistic
      @statistic = Statistic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def statistic_params
      params.require(:statistic).permit(:wins, :loses)
    end
end

app/helpers/statistics_helper.rb
module StatisticsHelper
end

app/views/statistics/_form.html.erb
<%= form_for(@statistic) do |f| %>
  <% if @statistic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@statistic.errors.count, "error") %> prohibited this statistic from being saved:</h2>

      <ul>
      <% @statistic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :wins %><br>
    <%= f.number_field :wins %>
  </div>
  <div class="field">
    <%= f.label :loses %><br>
    <%= f.number_field :loses %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/statistics/edit.html.erb
<h1>Editing Statistic</h1>

<%= render 'form' %>

<%= link_to 'Show', @statistic %> |
<%= link_to 'Back', statistics_path %>

app/views/statistics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Statistics</h1>

<table>
  <thead>
    <tr>
      <th>Wins</th>
      <th>Loses</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @statistics.each do |statistic| %>
      <tr>
        <td><%= statistic.wins %></td>
        <td><%= statistic.loses %></td>
        <td><%= link_to 'Show', statistic %></td>
        <td><%= link_to 'Edit', edit_statistic_path(statistic) %></td>
        <td><%= link_to 'Destroy', statistic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Statistic', new_statistic_path %>

app/views/statistics/new.html.erb
<h1>New Statistic</h1>

<%= render 'form' %>

<%= link_to 'Back', statistics_path %>

app/views/statistics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Wins:</strong>
  <%= @statistic.wins %>
</p>

<p>
  <strong>Loses:</strong>
  <%= @statistic.loses %>
</p>

<%= link_to 'Edit', edit_statistic_path(@statistic) %> |
<%= link_to 'Back', statistics_path %>