config/routes.rb
Rails.application.routes.draw do
  resources :friends
  resources :games
  resources :statistics
  resources :locations
  resources :pieces
  resources :pieces
 

   post 'chat/message' => 'chat#message'
   post 'games/move'  => 'games#move'

   post 'games/create' => 'games#create'
     get 'games/assets/:name.:ext', to: redirect('assets/%{name}.%{ext}')
 
   match ':controller(/:action(/:id))', :via => :get

  devise_for :users, :controllers => { :registrations => "registrations" }

   root 'home#title'

     get 'home/index' => 'home#index'

end

app/models/game.rb
class Game < ActiveRecord::Base
    belongs_to :user, :foreign_key => 'user_white_id'
    belongs_to :user, :foreign_key => 'user_black_id'

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  

  # GET /games/1
  # GET /games/1.json
  def show
    if(params.has_key?(:user) && params.has_key?(:color))
      @user =  params[:user]
      @color = params[:color]
      @game_id = params[:game_id]
      logger.error(@game_id)
      @game = Game.find(@game_id)
      @fen_string = @game.fen_string
      puts @game_id
      puts @fen_string
      if(params[:color] == "black")
          # @game = Game.find(@game_id)
          @game.user_black_id = @user
          @game.save
       end
    end
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new
    @game.user_white_id = current_user.id.to_i
    @game.save
    id = "game" + @game.id.to_s

    pusher_client.trigger(id, 'move', {
    name: current_user.name
    })

    @msg = {
        "color"  => "white",
        "user_id" => current_user.id,
        "game_id" => @game.id,
        "fen_string" => @game.fen_string,
       "redirect" => true,
       "redirectURL" => '/games/' + @game.id.to_s
      }
   render :json => @msg, status: :ok 
  end 

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def save_move(id, position)
   @game = Game.find(id)
   @game.fen_string = position
   @game.save
  end

 def move 
  id = "game" + params[:game_id].to_s
  pusher_client.trigger(id, 'move', {
    source: params[:source],
    target: params[:target],
    piece: params[:piece],
    newposition: params[:newposition]
  }, {
     socket_id: params[:socket_id]
    })

 save_move(params[:game_id],params[:newposition])
 
  if(params.has_key?(:status))
          #@game = Game.find(params[:game_id])
       if(params[:status] == "checkmate") 
           handle_checkmate(params[:winner])
       elsif (params[:status] == "draw")
            @game.destroy            
        
       elsif (params[:status] == "quit")
           @game.destroy
           
        end 
    end 
   respond_to :js
  
    #render :json , status: :ok
end

 def handle_checkmate(winner)
    if(@game.user_white_id == current_user.id)
      oponent_id = @game.user_black_id
    else
       oponent_id = @game.user_white_id
    end
    puts "oponent ID *****"
    puts oponent_id        
    stat = current_user.statistic
    oponent = User.find(oponent_id)
    oponent_stat = oponent.statistic
    if(winner == "yes")               
       stat.wins = stat.wins + 1
       oponent_stat.loses = oponent_stat.loses + 1
    else
       stat.loses = stat.loses + 1
       oponent_stat.wins = oponent_stat.wins + 1
    end
    stat.save
    oponent_stat.save
    @game.destroy
 end
 
 def  pusher_client 
  Pusher::Client.new(
    app_id: ENV['PUSHER_APP_ID'],
    key: ENV['PUSHER_KEY'],
    secret: ENV['PUSHER_SECRET'],
    encrypted: true
    )
 end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :public %><br>
    <%= f.check_box :public %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Games</h1>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th>Password</th>
      <th>Public</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.category %></td>
        <td><%= game.password %></td>
        <td><%= game.public %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<% content_for :javascript_includes do %>
  <%= javascript_include_tag "games.js" %>
  <%= javascript_include_tag "chess.js" %>
  <%= javascript_include_tag "chessboard-0.3.0.js" %>
  
<% end %>
<%= content_tag :div, class: "temp_information", 
     data: {user: @user, color: @color, game: @game_id, fen_string: @fen_string} do %>
<% end %>
<%= "game ID :" +  @game_id %>
<div class="container container-center " style="margin-top: 70px;">
<div class="row">
  <div class=" col-lg-5 col-md-5 col-sm-5">
    
         <script src="/assets/chess.js"></script>
        <div id="board" style="width: 400px"></div>
        <br><br>
        <p id="status">Status: <span id="status"></span></p>
      </div>

      <div id = "buttons" class=" col-lg-4 col-md-4 col-sm-4">
        <button type="submit" id = "quit" class="btn btn-warning" style="background: #540f2a;" value="quit">QUIT</button>
    </div>

  <div class=" col-lg-3 col-md-3 col-sm-3">
    <div class="chat-box-div">
      <div class="chat-box-head">
        GROUP CHAT 
      </div>
      <div class="panel-body chat-box-main">
        <div id="message">
          <div class="chat-box-left">
            Welcome User.
          </div>
          <div class="chat-box-name-left">
            Admin, 24-April 2016
          </div>
          <hr class="hr-clas" />
        </div>
      </div>
            
      <div class="chat-box-footer">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Enter Text Here..." id="chatbox">
          <span class="input-group-btn">
            <button class="btn btn-info" type="button" id="send">SEND</button>
          </span>
        </div>
      </div>
    </div>
  </div>
  </div>
</div>     

 